### ISSUE TITLE
suggest to point to relative dwca zip (e.g., dwca.zip) instead of url of github repo

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/AEC-DBCNet#1]
https://github.com/globalbioticinteractions/AEC-DBCNet/blob/28664b4c01b436e413027fe37b159a59b5b620ba/globi.json#L5

**Comment by seltmann** [comment]
What would the relative dwca zip look like?

**Comment by jhpoelen** [comment]
Please note I fixed the globi.json format, after your made the first release. Suggest to verify review logs and make another release. Apologies for the confusion.

**Comment by jhpoelen** [comment]
See https://github.com/globalbioticinteractions/AEC-DBCNet/runs/4111762993?check_suite_focus=true#step:4:42

```
Review of [globalbioticinteractions/AEC-DBCNet] included:
  - 113409 interaction(s)
  - 552 note(s)
  - 113411 info(s)

[globalbioticinteractions/AEC-DBCNet] has 552 reviewer note(s):
    514 target taxon name missing
     24 source taxon name missing: using institutionCode/collectionCode/collectionId/catalogNumber/occurrenceId as placeholder
     13 missing interaction type
      1 found unsupported interaction type with name: [null]
```

for review
